sudo: required
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
services:
  - docker
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
script:
  - CI=true npm test -- --coverage
  - CI=true npm run build
  - docker build -t web .
after_success:
  - echo 'exciting deployment goes here!'
